version: "3"

services: 
  mysql:
    image: mysql:latest
    volumes:
      - ./db_data
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafemati
      MYSQL_USER: cafemati
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306